source 'https://github.com/CocoaPods/Specs.git'
platform :ios,			'8.0'
inhibit_all_warnings!

target:'LCTextDemo'

pod 'Masonry', '1.1.0'
pod 'IQKeyboardManager', '6.2.0'
pod 'LCText', :path => '../../LCText'
